apiVersion: v2
name: kas
version: 0.0.1
description: TDF key access control service
type: application
maintainers:
  - name: Virtru
icon: https://avatars.githubusercontent.com/u/90051847?s=200&v=4
appVersion: 0.6.3a0
