name: Merge Request Tests
on: [pull_request]
jobs:
  scriptcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: ğŸ¦ª âœ” ğŸ§¼ğŸ§¼ğŸ§¼
        run: docker run --rm -v "$PWD:/mnt" --workdir "/mnt" "koalaman/shellcheck:v0.8.0" --color=always tools/*
      - name:  ğŸ¦ª âœ… ğŸ¦‡ğŸ¦‡ğŸ¦‡
        run: docker run --rm -v "$PWD:/mnt" --workdir "/mnt" bats/bats:1.5.0 tools/*.bats

  unittests:
    runs-on: ubuntu-latest
    needs:
      - scriptcheck
    steps:
      - uses: actions/checkout@v1
      - name: "ğŸ KAS Core Pytest"
        run: docker run --rm -v "$PWD:/mnt" --workdir "/mnt" "python:3.9" tools/monotest containers/kas/kas_core
      - name: "ğŸ KAS App Pytest"
        run: docker run --rm -v "$PWD:/mnt" --workdir "/mnt" "python:3.9" tools/monotest containers/kas/kas_app

  builds:
    runs-on: ubuntu-latest
    needs:
      - unittests
    steps:
      - uses: actions/checkout@v1
      - name: CI Build Local Docker Images
        run: make
